import type { AssemblySeed } from "../types";

/**
 * DEMO ASSEMBLY POINTS — evacuation muster points inside each hazard zone.
 *
 * Generated by snapping a ring of probes around every zone centre onto the
 * OpenStreetMap road network, keeping only hits that are on a road (within
 * ~1.5 km of the probe) and still inside the zone footprint, then picking the
 * most widely separated of them. So each point is real, road-served land inside
 * the hazard area — not the zone centroid, which is often water or forest and
 * makes a road router snap the departure kilometres away.
 *
 * Zones with several points let each evacuation batch leave from a different
 * part of the zone on a different road. Zones absent from this map fall back to
 * the zone centre (see `../assembly-points.ts`).
 *
 * Coordinates are road positions; the labels are demo data.
 */
export const MOCK_ASSEMBLY_POINTS: Record<string, AssemblySeed[]> = {
  "ls-kl-idk": [
    { dir: "North", lng: 76.9797, lat: 9.86823 },
    { dir: "East", lng: 76.9992, lat: 9.85006 },
    { dir: "North-east", lng: 76.9936, lat: 9.86338 },
  ],
  "ls-kl-wyd": [
    { dir: "North", lng: 76.1299, lat: 11.6284 },
    { dir: "East", lng: 76.1478, lat: 11.6109 },
    { dir: "North-east", lng: 76.1445, lat: 11.6238 },
  ],
  "ls-tn-nlg": [
    { dir: "North", lng: 76.7008, lat: 11.4234 },
    { dir: "East", lng: 76.714, lat: 11.41 },
    { dir: "North-east", lng: 76.7102, lat: 11.42 },
  ],
  "ls-ka-kdg": [
    { dir: "North", lng: 75.7302, lat: 12.4337 },
    { dir: "East", lng: 75.7441, lat: 12.4201 },
    { dir: "North-east", lng: 75.7395, lat: 12.4297 },
  ],
  "ls-mh-rgd": [
    { dir: "North", lng: 73.3185, lat: 18.8637 },
    { dir: "South-east", lng: 73.3268, lat: 18.8398 },
    { dir: "East", lng: 73.334, lat: 18.8452 },
  ],
  "ls-uk-rud": [
    { dir: "North", lng: 78.981, lat: 30.3087 },
    { dir: "East", lng: 79.0015, lat: 30.2902 },
    { dir: "North-east", lng: 78.9947, lat: 30.3036 },
  ],
  "ls-uk-chm": [
    { dir: "North", lng: 79.5581, lat: 30.5667 },
    { dir: "East", lng: 79.581, lat: 30.5504 },
    { dir: "North-east", lng: 79.575, lat: 30.5629 },
  ],
  "ls-uk-teh": [
    { dir: "North-east", lng: 78.4928, lat: 30.3904 },
    { dir: "South-east", lng: 78.4883, lat: 30.3686 },
    { dir: "East", lng: 78.4956, lat: 30.3792 },
  ],
  "ls-hp-kin": [
    { dir: "North", lng: 78.4393, lat: 31.5979 },
    { dir: "South-east", lng: 78.4562, lat: 31.5717 },
    { dir: "North-east", lng: 78.4529, lat: 31.5896 },
  ],
  "ls-hp-mnd": [
    { dir: "North", lng: 76.931, lat: 31.7237 },
    { dir: "East", lng: 76.9436, lat: 31.7107 },
    { dir: "North-east", lng: 76.9373, lat: 31.7205 },
  ],
  "ls-hp-sml": [
    { dir: "North", lng: 77.1707, lat: 31.1103 },
    { dir: "East", lng: 77.1805, lat: 31.1002 },
    { dir: "North-east", lng: 77.1782, lat: 31.1071 },
  ],
  "ls-sk-mgn": [
    { dir: "North-east", lng: 88.5468, lat: 27.7305 },
    { dir: "East", lng: 88.5509, lat: 27.7211 },
  ],
  "ls-sk-gtk": [
    { dir: "North", lng: 88.6097, lat: 27.3401 },
    { dir: "East", lng: 88.6212, lat: 27.33 },
    { dir: "North-east", lng: 88.618, lat: 27.3371 },
  ],
  "ls-wb-dar": [
    { dir: "North", lng: 88.2599, lat: 27.0534 },
    { dir: "East", lng: 88.2754, lat: 27.0399 },
    { dir: "North-east", lng: 88.2709, lat: 27.0496 },
  ],
  "ls-ar-sub": [
    { dir: "East", lng: 93.8461, lat: 27.6297 },
    { dir: "South-east", lng: 93.8413, lat: 27.6198 },
  ],
  "ls-ar-twg": [
    { dir: "North", lng: 91.8602, lat: 27.5898 },
    { dir: "East", lng: 91.8714, lat: 27.58 },
    { dir: "North-east", lng: 91.8689, lat: 27.5865 },
  ],
  "fl-as-dbr": [
    { dir: "North", lng: 94.9024, lat: 27.4852 },
    { dir: "East", lng: 94.9208, lat: 27.4708 },
    { dir: "North-east", lng: 94.9146, lat: 27.4829 },
  ],
  "fl-as-dhm": [
    { dir: "North", lng: 94.5799, lat: 27.4982 },
    { dir: "South", lng: 94.5793, lat: 27.4613 },
    { dir: "North-east", lng: 94.5951, lat: 27.4921 },
  ],
  "fl-as-brp": [
    { dir: "North", lng: 90.9997, lat: 26.333 },
    { dir: "East", lng: 91.0145, lat: 26.3202 },
    { dir: "North-east", lng: 91.0112, lat: 26.3303 },
  ],
  "fl-br-drb": [
    { dir: "North", lng: 85.9, lat: 26.1688 },
    { dir: "East", lng: 85.9198, lat: 26.15 },
    { dir: "North-east", lng: 85.9143, lat: 26.1628 },
  ],
  "fl-br-sup": [
    { dir: "North", lng: 86.602, lat: 26.1338 },
    { dir: "East", lng: 86.6162, lat: 26.1177 },
    { dir: "North-east", lng: 86.6108, lat: 26.1298 },
  ],
  "fl-br-mfp": [
    { dir: "North", lng: 85.3898, lat: 26.13 },
    { dir: "East", lng: 85.4012, lat: 26.12 },
    { dir: "North-east", lng: 85.3977, lat: 26.127 },
  ],
  "fl-up-gor": [
    { dir: "North", lng: 83.3702, lat: 26.7738 },
    { dir: "East", lng: 83.3854, lat: 26.76 },
    { dir: "North-east", lng: 83.3809, lat: 26.7698 },
  ],
  "fl-up-bal": [
    { dir: "North", lng: 84.15, lat: 25.7699 },
    { dir: "East", lng: 84.1607, lat: 25.7593 },
    { dir: "North-east", lng: 84.1573, lat: 25.7673 },
  ],
  "fl-wb-mur": [
    { dir: "North", lng: 88.2696, lat: 24.1938 },
    { dir: "East", lng: 88.2855, lat: 24.1799 },
    { dir: "North-east", lng: 88.2805, lat: 24.1898 },
  ],
  "fl-wb-mld": [
    { dir: "North", lng: 88.1399, lat: 25.0201 },
    { dir: "East", lng: 88.1519, lat: 25.0108 },
    { dir: "North-east", lng: 88.1476, lat: 25.0172 },
  ],
  "fl-od-knd": [
    { dir: "North", lng: 86.4187, lat: 20.5134 },
    { dir: "East", lng: 86.4349, lat: 20.4991 },
    { dir: "North-east", lng: 86.4308, lat: 20.5075 },
  ],
  "fl-od-jjp": [
    { dir: "North", lng: 86.3274, lat: 20.8597 },
    { dir: "East", lng: 86.3409, lat: 20.8498 },
    { dir: "North-east", lng: 86.3357, lat: 20.857 },
  ],
  "fl-kl-alp": [
    { dir: "North", lng: 76.34, lat: 9.51385 },
    { dir: "East", lng: 76.3534, lat: 9.50067 },
    { dir: "North-east", lng: 76.3498, lat: 9.50952 },
  ],
  "fl-ka-blr": [
    { dir: "North", lng: 77.6205, lat: 12.9497 },
    { dir: "East", lng: 77.6302, lat: 12.94 },
    { dir: "North-east", lng: 77.6272, lat: 12.9471 },
  ],
  "fl-tn-che": [
    { dir: "North", lng: 80.22, lat: 13.0539 },
    { dir: "East", lng: 80.2341, lat: 13.04 },
    { dir: "North-east", lng: 80.23, lat: 13.0498 },
  ],
  "cb-uk-chm": [
    { dir: "North", lng: 79.3505, lat: 30.4344 },
    { dir: "South-east", lng: 79.3597, lat: 30.4104 },
    { dir: "East", lng: 79.365, lat: 30.4163 },
  ],
  "cb-uk-utk": [
    { dir: "North", lng: 78.4518, lat: 30.7456 },
    { dir: "South", lng: 78.4503, lat: 30.7173 },
    { dir: "North-east", lng: 78.4579, lat: 30.7394 },
  ],
  "cb-uk-pth": [
    { dir: "North", lng: 80.2198, lat: 29.5898 },
    { dir: "East", lng: 80.2316, lat: 29.58 },
    { dir: "North-east", lng: 80.2272, lat: 29.5862 },
  ],
  "cb-hp-kul": [
    { dir: "North", lng: 77.1099, lat: 31.9781 },
    { dir: "East", lng: 77.1315, lat: 31.96 },
    { dir: "North-east", lng: 77.1252, lat: 31.973 },
  ],
  "cb-hp-kng": [
    { dir: "North", lng: 76.2697, lat: 32.1101 },
    { dir: "East", lng: 76.2816, lat: 32.1006 },
    { dir: "North-east", lng: 76.2787, lat: 32.1071 },
  ],
  "cb-jk-kis": [
    { dir: "North", lng: 75.7697, lat: 33.3239 },
    { dir: "East", lng: 75.7831, lat: 33.312 },
    { dir: "North-east", lng: 75.7761, lat: 33.3149 },
  ],
  "cb-jk-rmb": [
    { dir: "North", lng: 75.2405, lat: 33.2433 },
    { dir: "South", lng: 75.2396, lat: 33.2296 },
    { dir: "East", lng: 75.2467, lat: 33.2347 },
  ],
  "cb-ld-leh": [
    { dir: "North", lng: 77.58, lat: 34.1739 },
    { dir: "East", lng: 77.5966, lat: 34.1605 },
    { dir: "North-east", lng: 77.5907, lat: 34.1702 },
  ],
  "cb-ar-kam": [
    { dir: "North", lng: 92.3996, lat: 27.2645 },
    { dir: "East", lng: 92.4106, lat: 27.2603 },
    { dir: "North-east", lng: 92.4077, lat: 27.2657 },
  ],
  "ce-od-sat": [
    { dir: "North", lng: 86.899, lat: 20.701 },
    { dir: "South-west", lng: 86.8854, lat: 20.6679 },
    { dir: "West", lng: 86.8808, lat: 20.6762 },
  ],
  "ce-od-pur": [
    { dir: "North", lng: 85.83, lat: 19.8138 },
    { dir: "East", lng: 85.8444, lat: 19.8018 },
    { dir: "North-east", lng: 85.8393, lat: 19.8099 },
  ],
  "ce-wb-gho": [
    { dir: "North", lng: 88.1314, lat: 21.9174 },
    { dir: "North-west", lng: 88.1198, lat: 21.9138 },
    { dir: "North-east", lng: 88.1392, lat: 21.9136 },
  ],
  "ce-wb-dig": [
    { dir: "North", lng: 87.5301, lat: 21.6305 },
    { dir: "West", lng: 87.5193, lat: 21.6213 },
    { dir: "North-east", lng: 87.5374, lat: 21.6277 },
  ],
  "ce-ap-upp": [
    { dir: "North", lng: 82.3502, lat: 17.0987 },
    { dir: "South-west", lng: 82.3328, lat: 17.073 },
    { dir: "West", lng: 82.3303, lat: 17.0809 },
  ],
  "ce-ap-mch": [
    { dir: "North", lng: 81.1401, lat: 16.1837 },
    { dir: "East", lng: 81.1543, lat: 16.17 },
    { dir: "North-east", lng: 81.1501, lat: 16.1798 },
  ],
  "ce-ap-vsk": [
    { dir: "North", lng: 83.3, lat: 17.7299 },
    { dir: "East", lng: 83.3105, lat: 17.72 },
    { dir: "North-east", lng: 83.3072, lat: 17.7271 },
  ],
  "ce-tn-ngp": [
    { dir: "North", lng: 79.84, lat: 10.774 },
    { dir: "East", lng: 79.8504, lat: 10.7597 },
    { dir: "North-east", lng: 79.8499, lat: 10.7699 },
  ],
  "ce-tn-cud": [
    { dir: "North", lng: 79.7707, lat: 11.75 },
    { dir: "East", lng: 79.7794, lat: 11.7393 },
    { dir: "North-east", lng: 79.7771, lat: 11.747 },
  ],
  "ce-tn-kny": [
    { dir: "North", lng: 77.54, lat: 8.10008 },
    { dir: "East", lng: 77.55, lat: 8.08984 },
    { dir: "North-east", lng: 77.5471, lat: 8.09707 },
  ],
  "ce-kl-chl": [
    { dir: "North", lng: 76.2698, lat: 9.8384 },
    { dir: "East", lng: 76.2886, lat: 9.82 },
    { dir: "North-east", lng: 76.2788, lat: 9.82999 },
  ],
  "ce-ka-kwr": [
    { dir: "North", lng: 74.13, lat: 14.8192 },
    { dir: "East", lng: 74.14, lat: 14.8108 },
    { dir: "North-east", lng: 74.1373, lat: 14.8171 },
  ],
  "ce-mh-rtg": [
    { dir: "North", lng: 73.3101, lat: 17 },
    { dir: "East", lng: 73.3208, lat: 16.99 },
    { dir: "North-east", lng: 73.3173, lat: 16.9971 },
  ],
  "ce-gj-dwk": [
    { dir: "North-east", lng: 69.091, lat: 22.2474 },
    { dir: "South-east", lng: 69.0931, lat: 22.2301 },
    { dir: "East", lng: 69.0949, lat: 22.2391 },
  ],
  "fl-ka-kdg": [
    { dir: "North", lng: 75.9949, lat: 12.3379 },
    { dir: "East", lng: 76.007, lat: 12.3239 },
    { dir: "North-east", lng: 76.0059, lat: 12.3352 },
  ],
  "ce-kl-koz": [
    { dir: "North-east", lng: 75.7685, lat: 11.2686 },
    { dir: "South-east", lng: 75.7767, lat: 11.2346 },
    { dir: "East", lng: 75.7766, lat: 11.25 },
  ],
};
